--- 
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata: 
  name: podinfo
  namespace: flux-system
spec: 
  interval: 5m0s
  patches: 
    - 
      patch: "apiVersion: autoscaling/v2beta2\n\
          kind: HorizontalPodAutoscaler\n\
          metadata:\n\
          \x20 name: podinfo\n\
          spec:\n\
          \x20 minReplicas: 3             "
      target: 
        kind: HorizontalPodAutoscaler
        name: podinfo
  path: ./kustomize
  prune: true
  sourceRef: 
    kind: GitRepository
    name: podinfo
  targetNamespace: default
